add secretmgr read function and example
ivcap-works/legacy-ivcap-service-sdk-python pull request #42
Opened 2024-11-08 05:55 UTC by johnzhanghua

2024-11-12 02:29 UTC, maxott commented
I'm curious on why you are exposing the SecretService to the user:
```
    secret_service = get_secret_service()
    value = secret_service.read(args.secret_name)
```
Pretty much all the other SDK calls are primarily functional, so I would have expected something like
```
    value = get_secret(args.secret_name)
```
Any particular reason for that, beside future extensions - which then would just be additional methods on the SecretService class?

2024-11-12 02:33 UTC, johnzhanghua commented
> I'm curious on why you are exposing the SecretService to the user:
> 
> ```
>     secret_service = get_secret_service()
>     value = secret_service.read(args.secret_name)
> ```
> 
> Pretty much all the other SDK calls are primarily functional, so I would have expected something like
> 
> ```
>     value = get_secret(args.secret_name)
> ```
> 
> Any particular reason for that, beside future extensions - which then would just be additional methods on the SecretService class?

Good point.  It was following the queue service, thought it was the pattern. :)   Happy to simplify it.

2024-11-12 03:03 UTC, johnzhanghua commented
Fixed.

2024-11-12 04:07 UTC, bclews requested changes
Nice work, I have added a few minor comments.

2024-11-12 04:07 UTC, bclews commented on examples/secret/Makefile
> +	--build-arg TIMEZONE=${BUILD_TZ} \
`${BUILD_TZ}` is referenced, but it does not seem to be  defined.

2024-11-12 04:07 UTC, bclews commented on examples/secret/secret.py
> +    logger.info(f"read out value { value }")
I could see myself accidentally running this in production 🤪
```python
# ALERT, don't log it in prod, its only for demo purpose
logger.info(f"read out value { value }")
```

Can we raise an exception instead? Something like...
```python
try:
    value = get_secret(args.secret_name)
    logger.info("Successfully retrieved secret")  
    .
    .
except (ValueError, SecretRetrievalError) as e:
    logger.error(f"Failed to retrieve secret: {e}")
    raise
```

**Edit:** ...or maybe make the comment bigger and more obnoxious :)

2024-11-12 04:07 UTC, bclews commented on examples/secret/secret.py
> +def get_secret_service(args: ServiceArgs, logger: logging):
Nit-picky but `get_secret_service` function name is slightly ambiguous. Maybe `retrieve_secret` or `fetch_secret_value` for clarity?

2024-11-12 04:07 UTC, bclews commented on src/ivcap_sdk_service/cio/ivcap_io_adapter.py
> +            return []
Should this be `return ""` to match the function definition, which says we are returning a string (ie `-> str`)

2024-11-12 04:07 UTC, bclews commented on src/ivcap_sdk_service/cio/ivcap_io_adapter.py
> +            logger.error(f"Failed to read seceret: {e}")
Small typo `seceret`

2024-11-12 04:53 UTC, johnzhanghua commented on examples/secret/Makefile
> +	--build-arg TIMEZONE=${BUILD_TZ} \
🤣  , some code copied over.

2024-11-12 04:59 UTC, johnzhanghua commented on examples/secret/secret.py
> +def get_secret_service(args: ServiceArgs, logger: logging):
Is it, its passed in as a 'service' function parameter.  Might just call it 'service'.

2024-11-12 05:16 UTC, johnzhanghua commented on src/ivcap_sdk_service/cio/ivcap_io_adapter.py
> +            return []
I think it better to raise Exception in that case.

2024-11-14 02:51 UTC, bclews approved these changes

2024-11-14 04:39 UTC, merged